Role.create(name: :admin)
Role.create(name: :doc)
Role.create(name: :labtech)
Role.create(name: :pharmacist)
Role.create(name: :accountant)

user1 = User.create(username: 'Admin', email: 'admin@gmail.com', password: '123456', password_confirmation: '123456')
user1.add_role(:admin)
user2 = User.create(username: 'Doctor', email: 'doctor@gmail.com', password: '123456', password_confirmation: '123456')
user2.add_role(:doc)
user3 = User.create(username: 'Lab', email: 'lab@gmail.com', password: '123456', password_confirmation: '123456')
user3.add_role(:labtech)
user4 = User.create(username: 'Pharmacist', email: 'pharmacist@gmail.com', password: '123456', password_confirmation: '123456')
user4.add_role(:pharmacist)
user5 = User.create(username: 'Accountant', email: 'accountant@gmail.com', password: '123456', password_confirmation: '123456')
user5.add_role(:accountant)
